// <auto-generated />
using System;
using DotNetCore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCore.API.Migrations
{
    [DbContext(typeof(OnlineStoreDbContext))]
    [Migration("20240517201019_addInitialMigration")]
    partial class addInitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31190107-d560-434e-959e-dafc7be85a98"),
                            Code = "GP",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9275),
                            Description = "Gauteng Province",
                            Name = "Gauteng",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9275)
                        },
                        new
                        {
                            Id = new Guid("c565f77b-b5e1-4025-8813-e99b621ad187"),
                            Code = "GP",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9277),
                            Description = "KwaZulu-Natal",
                            Name = "KwaZulu-Natal",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9277)
                        },
                        new
                        {
                            Id = new Guid("4bb05fd0-1489-4c49-ad27-8216b4d6a516"),
                            Code = "EC",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9279),
                            Description = "Eastern Cape",
                            Name = "Eastern Cape",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9279)
                        },
                        new
                        {
                            Id = new Guid("260ac91a-ab3f-4717-bfe9-13fc52c4d8d8"),
                            Code = "FS",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9280),
                            Description = "Free State",
                            Name = "Free State",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9281)
                        },
                        new
                        {
                            Id = new Guid("7a799857-3ee9-4942-8f4e-eb70a02f2378"),
                            Code = "LP",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9282),
                            Description = "Limpopo",
                            Name = "Limpopo",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9282)
                        },
                        new
                        {
                            Id = new Guid("8ab903a5-0b44-4c2f-8402-dfc7f3df8e5e"),
                            Code = "MP",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9291),
                            Description = "Mpumalanga",
                            Name = "Mpumalanga",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9291)
                        },
                        new
                        {
                            Id = new Guid("724cb957-06c4-40de-aa86-b3ecf46b99f1"),
                            Code = "NW",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9292),
                            Description = "North West",
                            Name = "North West",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9292)
                        },
                        new
                        {
                            Id = new Guid("15eb53f2-37a8-4c13-b0c2-2e4aa4fc782d"),
                            Code = "NC",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9294),
                            Description = "Northern Cape",
                            Name = "Northern Cape",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9294)
                        },
                        new
                        {
                            Id = new Guid("cd6d1690-42fe-4194-9471-fd62062cb0ae"),
                            Code = "WC",
                            CreatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9295),
                            Description = "Western Cape",
                            Name = "Western Cape",
                            UpdatedDate = new DateTime(2024, 5, 17, 20, 10, 19, 30, DateTimeKind.Utc).AddTicks(9295)
                        });
                });

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Product", b =>
                {
                    b.HasOne("DotNetCore.API.Models.Domain.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
