// <auto-generated />
using System;
using DotNetCore.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DotNetCore.API.Migrations
{
    [DbContext(typeof(OnlineStoreDbContext))]
    [Migration("20240514064147_UdateDateTimeInitialValueForRegions")]
    partial class UdateDateTimeInitialValueForRegions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("abf169d4-1b6c-4df8-9340-6e1d909d037e"),
                            Code = "GP",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5933),
                            Description = "Gauteng Province",
                            Name = "Gauteng",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5934)
                        },
                        new
                        {
                            Id = new Guid("fd618ce5-294e-4a62-bbfb-c43ae0f013c8"),
                            Code = "GP",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5936),
                            Description = "KwaZulu-Natal",
                            Name = "KwaZulu-Natal",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5937)
                        },
                        new
                        {
                            Id = new Guid("97db5a1f-16b1-4c37-b65c-1b71c42d3c96"),
                            Code = "EC",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5938),
                            Description = "Eastern Cape",
                            Name = "Eastern Cape",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5938)
                        },
                        new
                        {
                            Id = new Guid("1592448c-d360-4923-a215-9a0d3b72ce04"),
                            Code = "FS",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5939),
                            Description = "Free State",
                            Name = "Free State",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5940)
                        },
                        new
                        {
                            Id = new Guid("73152684-a021-4570-9c65-a25ac464a95f"),
                            Code = "LP",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5949),
                            Description = "Limpopo",
                            Name = "Limpopo",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5949)
                        },
                        new
                        {
                            Id = new Guid("6d2d4562-bda8-47c1-99bf-269fe0f4e316"),
                            Code = "MP",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5951),
                            Description = "Mpumalanga",
                            Name = "Mpumalanga",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5951)
                        },
                        new
                        {
                            Id = new Guid("f812bcff-cf06-4139-8072-ab9337cf46d4"),
                            Code = "NW",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5952),
                            Description = "North West",
                            Name = "North West",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5953)
                        },
                        new
                        {
                            Id = new Guid("34a5804b-2d2d-46d4-a392-88db2c61e74a"),
                            Code = "NC",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5954),
                            Description = "Northern Cape",
                            Name = "Northern Cape",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5955)
                        },
                        new
                        {
                            Id = new Guid("fce71014-9759-4fa3-8acb-235a49d10e70"),
                            Code = "WC",
                            CreatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5956),
                            Description = "Western Cape",
                            Name = "Western Cape",
                            UpdatedDate = new DateTime(2024, 5, 14, 6, 41, 46, 898, DateTimeKind.Utc).AddTicks(5956)
                        });
                });

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Product", b =>
                {
                    b.HasOne("DotNetCore.API.Models.Domain.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DotNetCore.API.Models.Domain.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
